trigger:
  branches:
    include:
      - main  # Triggers pipeline when code is pushed to 'main'

pool:
  name: Default
  demands:
    - Agent.Name -equals opsi  # Ensures the job runs on the agent named 'opsi'

variables:
- group: opsi-credentials  # Make sure this group exists and includes all required variables

steps:
- checkout: self  # Use correct keyword instead of 'task: Checkout@1'
  displayName: "Checkout code"

- script: chmod +x scripts/deploy_opsi.sh
  displayName: "Make script executable"

- script: ./scripts/deploy_opsi.sh
  displayName: "Trigger OpSi Software Deployment"
  env:
    OPSI_USER: $(OPSI_USER)
    OPSI_PASS: $(OPSI_PASS)
    OPSI_HOST: $(OPSI_HOST)
    PRODUCT_ID: $(PRODUCT_ID)
    CLIENT_ID: $(CLIENT_ID)
