trigger:
  branches:
    include:
      - main  # or any branch you want to trigger from

pool:
  name: Default  # Your agent pool name
  demands:
    - Agent.Name -equals opsi  # This will ensure it runs on your "opsi" agent

variables:
- group: opsi-credentials  # This loads all your secret and non-secret variables

steps:
- task: Checkout@1
  displayName: "Checkout code"

- script: chmod +x scripts/deploy_opsi.sh
  displayName: "Make script executable"

- script: ./scripts/deploy_opsi.sh
  displayName: "Trigger OpSi Software Deployment"
  env:
    OPSI_USER: $(OPSI_USER)
    OPSI_PASS: $(OPSI_PASS)
    OPSI_HOST: $(OPSI_HOST)
    PRODUCT_ID: $(PRODUCT_ID)
    CLIENT_ID: $(CLIENT_ID)

